# Generated by Django 6.0 on 2025-12-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoasset',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='crypto_images/', verbose_name='Изображение'),
        ),
    ]
